using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

namespace Experion.Api.Providers;

/// <summary>
/// Deterministic 128-dim "embedding" derived from a normalized bag-of-words hash.
/// Same text → same vector. Similar text → similar vector. Good enough to
/// demonstrate caching, semantic action matching, and KB retrieval without Azure keys.
/// </summary>
public class MockEmbeddingProvider : IEmbeddingProvider
{
    private const int Dim = 128;
    private static readonly Regex TokenRx = new(@"[a-z0-9]+", RegexOptions.Compiled);

    public Task<float[]> EmbedAsync(string text, CancellationToken ct = default)
    {
        var vec = new float[Dim];
        if (string.IsNullOrWhiteSpace(text)) return Task.FromResult(vec);

        var tokens = TokenRx.Matches(text.ToLowerInvariant())
            .Select(m => m.Value)
            .Where(t => t.Length > 1)
            .ToList();

        foreach (var token in tokens)
        {
            using var md5 = MD5.Create();
            var bytes = md5.ComputeHash(Encoding.UTF8.GetBytes(token));
            // Spread across dimensions
            for (int i = 0; i < bytes.Length; i++)
            {
                int idx = (bytes[i] + i * 7) % Dim;
                float sign = (bytes[(i + 1) % bytes.Length] & 1) == 0 ? 1f : -1f;
                vec[idx] += sign * (1f + (bytes[i] / 255f));
            }
        }

        // L2 normalize
        double norm = 0;
        for (int i = 0; i < Dim; i++) norm += vec[i] * vec[i];
        if (norm > 0)
        {
            float inv = (float)(1.0 / Math.Sqrt(norm));
            for (int i = 0; i < Dim; i++) vec[i] *= inv;
        }
        return Task.FromResult(vec);
    }
}

/// <summary>
/// Mock LLM that performs lightweight extractive RAG over the provided context.
/// It does NOT call any external service. The system prompt may pass a JSON-ish
/// "task" directive that this mock recognises (e.g. {"task":"draft_recommendation"}).
/// </summary>
public class MockLlmProvider : ILlmProvider
{
    public Task<string> CompleteAsync(string systemPrompt, string userPrompt, CancellationToken ct = default)
    {
        // Heuristic: if the userPrompt contains a "## CONTEXT" section, do extractive RAG.
        string answer;

        var contextMatch = Regex.Match(userPrompt, @"## CONTEXT\s*\n([\s\S]+?)(\n## |$)");
        var questionMatch = Regex.Match(userPrompt, @"## QUESTION\s*\n([\s\S]+?)(\n## |$)");

        var question = questionMatch.Success ? questionMatch.Groups[1].Value.Trim() : userPrompt.Trim();
        var ctx = contextMatch.Success ? contextMatch.Groups[1].Value.Trim() : "";

        if (systemPrompt.Contains("draft_recommendation", StringComparison.OrdinalIgnoreCase))
        {
            answer = "Looks like you've been browsing for a bit — would you like me to summarise the page, " +
                     "compare what you're looking at, or take you to checkout? I can also surface popular " +
                     "alternatives in this category.";
        }
        else if (string.IsNullOrEmpty(ctx))
        {
            answer = $"I don't have specific knowledge about that yet. Here's a generic answer for: \"{Truncate(question, 200)}\". " +
                     "Wire up Azure OpenAI in appsettings.json (Llm:Provider = \"AzureOpenAI\") to get real responses.";
        }
        else
        {
            // Pick the 2 most relevant lines from context by simple keyword overlap with the question.
            var qTokens = Tokenise(question).ToHashSet();
            var lines = ctx.Split('\n').Where(l => l.Trim().Length > 0).ToList();
            var ranked = lines
                .Select(l => new { Line = l, Score = Tokenise(l).Count(t => qTokens.Contains(t)) })
                .Where(x => x.Score > 0)
                .OrderByDescending(x => x.Score)
                .Take(3)
                .Select(x => x.Line.Trim())
                .ToList();

            if (ranked.Count == 0)
            {
                answer = $"Based on the available knowledge base I couldn't find a direct answer for: \"{Truncate(question, 200)}\". " +
                         $"You might rephrase, or I can connect you to support.";
            }
            else
            {
                var bullets = string.Join("\n", ranked.Select(r => $"• {r}"));
                answer = $"Here's what I found:\n\n{bullets}\n\n(Answer generated by the mock LLM provider — set Llm:Provider to \"AzureOpenAI\" for real generation.)";
            }
        }

        return Task.FromResult(answer);
    }

    private static IEnumerable<string> Tokenise(string s) =>
        Regex.Matches(s.ToLowerInvariant(), @"[a-z0-9]+").Select(m => m.Value).Where(t => t.Length > 2);

    private static string Truncate(string s, int n) => s.Length > n ? s[..n] + "…" : s;
}
